version: 0.2

phases:
  install:
    commands:
      - echo Entered the install phase...
      - id
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - php -v
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`

# See Build specification reference for CodeBuild
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
